version: "3.8"
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - "52181:2181"
      - "52888:2888"
      - "53888:3888"
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "59092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - "58083:8083"
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension
  apicurio:
    image: apicurio/apicurio-registry-sql:2.4.x-release
    ports:
      - "58002:8080"
    environment:
      REGISTRY_DATASOURCE_URL: jdbc:postgresql://postgres/postgres?currentSchema=apicurio
      REGISTRY_DATASOURCE_USERNAME: postgres
      REGISTRY_DATASOURCE_PASSWORD: postgres
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "58000:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./conf/kafka-ui/conf.yml:/etc/kafkaui/dynamic_config.yaml
  debezium-ui:
    # TODO: Check again for the correct image architecture.
    platform: linux/x86_64
    image: quay.io/debezium/debezium-ui:${DEBEZIUM_VERSION}
    ports:
      - "58001:8080"
    links:
      - connect
    environment:
      KAFKA_CONNECT_URIS: http://connect:8083